### ISSUE TITLE
Apps freezes, akbaqka.dll & scnetworkgateway

### ISSUE THREAD

**Issue by Ripipip** [Starcounter/Starcounter#2769]
I am running my apps perfectly fine for some time (up to 12 hours) and then suddently the apps freezes, no error is shown, scnetworkgateway shows high cpu usage and akbakqa.dll drains cpu in analyzer. 

There doesn't seem to be any correlation between this crash and the load. (It has crashed last night at 4 AM which should be at a time with a very low load). 

How can I investigate this further?

**Comment by alemoi** [comment]
Thanks for reporting! 

I just have checked and Gateway can start spinning in two possible scenarios: 

1. The database always sends something on the gateway, e.g. intensive push on websockets.

2. The gateway is not able to push to database because either IPC channels are full or gateway can't obtain IPC chunks. I guess it because the chunks are leaked somewhere and gateway can't get any so it spins and spins.

I will try to provide some diagnostics to see how many IPC chunks are available in the system and how much chunks are currently in IPC channels.

I suppose  `akbakqa.dll ` is an SQL codegen DLL that is loaded. It means that indexes are not utilized on some SQL requests.

**Comment by alemoi** [comment]
When you have this situation, how many threads does the sccode.exe process have (look in task manager)?

**Comment by alemoi** [comment]
Via the commit 453fe6c01387d80e1a322e6eff3d572e5b5b125b I added the statistics to see current number of available chunks in IPC shared interface. @Ripipip when the stuck situation occurs, can you please go to `http://127.0.0.1:8181/gwstats` and copy here the databases section, like this:
```
databases: [
{
name: "administrator",
index: 0,
NumAvailableChunks: 64512
}
],
```
Thank you!

**Comment by alemoi** [comment]
By the way what version of SC do you use?

**Comment by dan31** [comment]
I will answer.
Polyjuice-DevelopDailyBuilds-2.0.9585 (May 8, 2015 10:49:25 AM)
Quite old, but I wonder why daily, is it intentional?

**Comment by alemoi** [comment]
Added statistics for chunks pushed to channels: 
```
databases: [
{
name: "administrator",
index: 0,
NumAvailableChunks: 64512,
ChannelsChunks: "[0,0] [0,0] [0,0] [0,0] [0,0] [0,0] [0,0] [0,0]"
}
],
```

**Comment by Ripipip** [comment]
@dan31 I think it were a fix that was pushed to that build and thats why we started to use that particular build. 

@alemoi I will  check for number of threads when it freezes, but I have to be able to monitor it and I've been busy this weekend. Regarding the added statistics, how do I use that?

**Comment by alemoi** [comment]
We think we identified an issue and working on bugfix now, which will be soon, hopefully tomorrow, available.

**Comment by Ripipip** [comment]
@alemoi I caught the error again and were able to check the number of threads  in sccode.exe: 39

**Comment by alemoi** [comment]
Thank you!  In this stuck situation, can you please also go to `http://127.0.0.1:8181/gwstats` and copy here the databases section, like shown above?
In any case, we have fixed a few problems related with this. Patches will be available in this nightly build. Let's do a follow up with @dan31 regarding the upgrade!

**Comment by Ripipip** [comment]
I removed the handlers and this is what I could see on that url. 

{
    "ports": [
        {
            "port": 8181,
            "acceptingSockets": 22,
            "activeSockets": "33-0",
            "registeredUris": []
        },
        {
            "port": 9191,
            "acceptingSockets": 1,
            "activeSockets": "1-0",
            "registeredUris": [],
            "registeredWsChannels": []
        },
        {
            "port": 8080,
            "acceptingSockets": 17,
            "activeSockets": "6975-6975",
            "registeredUris": [],
            "registeredWsChannels": [
                {
                    "wschannel": "administratorjsonpatchws",
                    "location": "administrator",
                    "application": "NoApp"
                },
                {
                    "wschannel": "defaultjsonpatchws",
                    "location": "default",
                    "application": "NoApp"
                }
            ]
        }
    ],
    "databases": [
        {
            "name": "administrator",
            "index": 0
        },
        {
            "name": "default",
            "index": 1
        }
    ],
    "workers": [
        {
            "id": 0,
            "bytesReceived": 1021396676,
            "packetsReceived": 2103816,
            "bytesSent": 1246937792,
            "packetsSent": 2021939,
            "allocatedChunks": "14, 14421, 6, 2, 0, 0, 1"
        },
        {
            "id": 1,
            "bytesReceived": 1032804739,
            "packetsReceived": 2102627,
            "bytesSent": 1171804662,
            "packetsSent": 2019929,
            "allocatedChunks": "9, 14382, 3, 2, 0, 0, 0"
        }
    ],
    "global": {
        "allWorkersLastSecond": {
            "receivedTimes": 38,
            "httpRequests": 37,
            "receiveBandwidth": 0.132312,
            "sentTimes": 1,
            "sendBandwidth": 0.02812
        }
    }
}

**Comment by alemoi** [comment]
For this we need you to install the latest version. Should we coordinate this with @dan31 ?

**Comment by alemoi** [comment]
These problems should be resolved now. Is that correct @dan31 ?

**Comment by dan31** [comment]
akbaqka.dll isn't solved yet. @Ripipip, can you make a separate issue for it?
