### ISSUE TITLE
Autostart (OFF) and Lock buttons don't stay on same row

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2848]
![image](https://cloud.githubusercontent.com/assets/6435556/9300473/0120b952-44cf-11e5-9ca3-ffb4ee49f9c5.png)

@andwah take a look, please.

**Comment by miyconst** [comment]
@andwah, this is fixed, right?

**Comment by andwah** [comment]
> @andwah, this is fixed, right?

Yes, 
Note that wrapping can still occur depending on page width
