### ISSUE TITLE
Missing AppName and PartialId properties in responses mapped with Polyjuice.OntologyMap

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#2902]
Procurement application has mapping:

```cs
Polyjuice.OntologyMap("/procurement/purchase-order/@w", "/so/event/@w", null, null);
```

If this mapping enabled, then response for `/procurement/purchase-order/@w` lacks `AppName` and `PartialId` properties:

![image](https://cloud.githubusercontent.com/assets/6435556/10074309/6fc31350-62cf-11e5-97d9-70e8a7d406f1.png)

But it should be:

![image](https://cloud.githubusercontent.com/assets/6435556/10074313/7fbab222-62cf-11e5-9a69-5bb2c5e7ada6.png)

Here are the full json trees:

```json
{"Launcher":{"Html":"","appName":"Procurement","_juicyTilesSetup":"","_partialId":"","_editorOpened":false},"Procurement":{"Html":"/Procurement/viewmodels/LauncherWrapperPage.html","CurrentPage":{"Procurement":{"Html":"/Procurement/viewmodels/PurchaseOrderPage.html","BeginTime":"2015-09-24 12:43:34Z","PurchaseOrderNo":1,"SupplierName$":"Starcounter","SupplierNameClick$":0,"ClearFoundSuppliers$":0,"FoundSuppliers":[],"PurchaseOrderItems":[{"SelectedProductIndex$":0,"Name$":"i","ClearFoundProducts$":0,"FoundProducts":[],"Price$":0,"Quantity$":1,"TotalPrice":0,"Focus$":0,"Delete$":0}],"AddPurchaseOrderItem$":0,"TotalPrice":0,"SaveChanges$":0,"Cancel$":0,"RedirectUrl$":""},"Html":"/polyjuice/htmlmerger?Procurement=/Procurement/viewmodels/PurchaseOrderPage.html","AppName":"Procurement","PartialId":"/Procurement/viewmodels/PurchaseOrderPage.html","juicyTilesSetup":{"id":"root","direction":"horizontal","gutter":15,"items":[{"precalculateHeight":true,"width":"100%","widthFlexible":true,"priority":0.5,"id":"Procurement/0","height":84,"hidden":false,"itemName":"New purchase order"},{"gutter":0,"items":[{"precalculateHeight":true,"width":100,"widthFlexible":false,"priority":0.4444444444444444,"id":"Procurement/1","height":32,"hidden":false,"itemName":"Order date"},{"precalculateHeight":true,"width":900,"widthFlexible":true,"priority":0.3950617283950617,"id":"Procurement/2","height":37,"hidden":false,"itemName":"<div>"},{"precalculateHeight":true,"width":100,"widthFlexible":false,"priority":0.3511659807956104,"id":"Procurement/3","height":32,"hidden":false,"itemName":"Supplier"},{"precalculateHeight":true,"width":900,"widthFlexible":true,"priority":0.312147538484987,"id":"Procurement/4","height":37,"hidden":false,"itemName":"<div>"}],"id":"root_1","priority":0.4444444444444444,"width":"100%","height":106,"hidden":false,"itemName":"Group 2","widthFlexible":true,"precalculateHeight":true,"tightGroup":true},{"precalculateHeight":true,"width":"100%","widthFlexible":true,"priority":0.27746447865332174,"id":"Procurement/5","height":161,"hidden":false,"itemName":"No items in this ord …","heightDynamic":true},{"gutter":15,"items":[{"precalculateHeight":true,"width":115,"widthFlexible":false,"priority":0.24663509213628598,"id":"Procurement/6","height":36,"hidden":false,"itemName":"Save changes","precalculateWidth":true},{"precalculateHeight":true,"width":128,"widthFlexible":false,"priority":0.21923119301003197,"id":"Procurement/7","height":36,"hidden":false,"itemName":"Add order item","precalculateWidth":true},{"precalculateHeight":true,"width":75,"widthFlexible":false,"priority":0.19487217156447284,"id":"Procurement/8","height":36,"hidden":false,"itemName":"Cancel","precalculateWidth":true}],"id":"root_0","priority":0.24663509213628598,"width":"100%","height":72,"hidden":false,"itemName":"Group 1","widthFlexible":true,"precalculateHeight":true,"tightGroup":true}],"width":1000,"precalculateHeight":true,"itemName":"PurchaseOrderPage.html"}}},"Html":"/polyjuice/htmlmerger?Procurement=/Procurement/viewmodels/LauncherWrapperPage.html"}
```

```json
{"Launcher":{"Html":"","appName":"Procurement","_juicyTilesSetup":"","_partialId":"","_editorOpened":false},"Procurement":{"Html":"/Procurement/viewmodels/LauncherWrapperPage.html","CurrentPage":{"Procurement":{"Html":"/Procurement/viewmodels/PurchaseOrderPage.html","BeginTime":"2015-09-24 12:43:34Z","PurchaseOrderNo":1,"SupplierName$":"Starcounter","SupplierNameClick$":0,"ClearFoundSuppliers$":0,"FoundSuppliers":[],"PurchaseOrderItems":[{"SelectedProductIndex$":0,"Name$":"i","ClearFoundProducts$":0,"FoundProducts":[],"Price$":0,"Quantity$":1,"TotalPrice":0,"Focus$":0,"Delete$":0}],"AddPurchaseOrderItem$":0,"TotalPrice":0,"SaveChanges$":0,"Cancel$":0,"RedirectUrl$":""},"Html":"/polyjuice/htmlmerger?Procurement=/Procurement/viewmodels/PurchaseOrderPage.html","AppName":"Procurement","PartialId":"/Procurement/viewmodels/PurchaseOrderPage.html","juicyTilesSetup":{"id":"root","direction":"horizontal","gutter":15,"items":[{"precalculateHeight":true,"width":"100%","widthFlexible":true,"priority":0.5,"id":"Procurement/0","height":84,"hidden":false,"itemName":"New purchase order"},{"gutter":0,"items":[{"precalculateHeight":true,"width":100,"widthFlexible":false,"priority":0.4444444444444444,"id":"Procurement/1","height":32,"hidden":false,"itemName":"Order date"},{"precalculateHeight":true,"width":900,"widthFlexible":true,"priority":0.3950617283950617,"id":"Procurement/2","height":37,"hidden":false,"itemName":"<div>"},{"precalculateHeight":true,"width":100,"widthFlexible":false,"priority":0.3511659807956104,"id":"Procurement/3","height":32,"hidden":false,"itemName":"Supplier"},{"precalculateHeight":true,"width":900,"widthFlexible":true,"priority":0.312147538484987,"id":"Procurement/4","height":37,"hidden":false,"itemName":"<div>"}],"id":"root_1","priority":0.4444444444444444,"width":"100%","height":106,"hidden":false,"itemName":"Group 2","widthFlexible":true,"precalculateHeight":true,"tightGroup":true},{"precalculateHeight":true,"width":"100%","widthFlexible":true,"priority":0.27746447865332174,"id":"Procurement/5","height":161,"hidden":false,"itemName":"No items in this ord …","heightDynamic":true},{"gutter":15,"items":[{"precalculateHeight":true,"width":115,"widthFlexible":false,"priority":0.24663509213628598,"id":"Procurement/6","height":36,"hidden":false,"itemName":"Save changes","precalculateWidth":true},{"precalculateHeight":true,"width":128,"widthFlexible":false,"priority":0.21923119301003197,"id":"Procurement/7","height":36,"hidden":false,"itemName":"Add order item","precalculateWidth":true},{"precalculateHeight":true,"width":75,"widthFlexible":false,"priority":0.19487217156447284,"id":"Procurement/8","height":36,"hidden":false,"itemName":"Cancel","precalculateWidth":true}],"id":"root_0","priority":0.24663509213628598,"width":"100%","height":72,"hidden":false,"itemName":"Group 1","widthFlexible":true,"precalculateHeight":true,"tightGroup":true}],"width":1000,"precalculateHeight":true,"itemName":"PurchaseOrderPage.html"}}},"Html":"/polyjuice/htmlmerger?Procurement=/Procurement/viewmodels/LauncherWrapperPage.html","AppName":"Procurement","PartialId":"/Procurement/viewmodels/LauncherWrapperPage.html","juicyTilesSetup":{"id":"root","direction":"rightDown","gutter":0,"items":[{"heightAuto":true,"width":"100%","heightDynamic":true,"priority":0.5,"id":"Procurement/0","height":219,"itemName":"New purchase order","hidden":false,"widthFlexible":true}],"width":1000,"heightAuto":true,"itemName":"LauncherWrapperPage.html","precalculateHeight":true}}
```

@alemoi says that it might be a problem with json serializer, @chrhol could you please take a look?

I will comment out the map and migrate Procurement app to Polymer 1.x, so it will be easy to test.

**Comment by warpech** [comment]
@miyconst is this a showstopper for us? What's the consequence of that?

**Comment by miyconst** [comment]
Yes, it is a showstopper. Without the AppName we don't know to which app the result belongs, and `juicy-display-router` does not work.

It happens only if mapping applied.

**Comment by warpech** [comment]
In what Starcounter version did it stop working? It seems ok in 2.0.3343.3

**Comment by miyconst** [comment]
I can't check my office pc right now, but I believe it was `2.0.3343.3`, and the latest version `2.1.4.3` has the same issue.

**Comment by miyconst** [comment]
Procurement app is now pushed, so it is easy to test.

Test steps:

1. Run SysUpgrade, Launcher, Procurement app.
2. Create a purchase order in the Procurement app.
3. Go to edit page.
4. Reload page.
6. Check the console, there will be an error: `Error: juicy-display-router: display-selector cannot be empty`.
7. Check the viewmodel.

**Comment by warpech** [comment]
This is not a new bug, since I was also able to reproduce it in playground running Starcounter 2.0.10293.2 (14 Aug 2015). It may be many months older.

Link to reproducing: http://boden-848.mysampleapp.com/Procurement/purchase-order/Hd (note the similar error message to what @miyconst reported)

Note that app main page does not have that problem: http://boden-848.mysampleapp.com/Procurement
Note that other app (People) also does not have that problem: http://boden-848.mysampleapp.com/people/persons/Mn

This looks like a bug in JSON serializer. Assigning to @chrhol 

This is the same issue as point 2 in https://github.com/Polyjuice/GoogleSignIn/issues/6

**Comment by miyconst** [comment]
@warpech thank you for the investigation, I was going to do that.

**Comment by chrhol** [comment]
I will look into it. Have reproduced it following the steps from @miyconst

**Comment by chrhol** [comment]
I'm not sure yet if the bug is in the serializer or the merger (or possible some place before the merger is called). There is a value in the Json class, `_activeAppName` that isn't set correctly when the whole page is refreshed.

I will try to figure out what this value is for and probably try to refactor the code around it since it is not that easy to understand why it is needed :)

**Comment by miyconst** [comment]
Some input from @malx122:

```
[{"op":"replace","path":"/_ver#s","value":1},{"op":"test","path":"/_ver#c$","value":0},{"op":"replace","path":"/workspaces/1/SignIn/Username$","value":""},{"op":"replace","path":"/workspaces/1/SignIn/Password$","value":""},{"op":"replace","path":"/workspaces/1/SignIn/IsSignedIn","value":false},{"op":"replace","path":"/workspaces/1/SignIn/Message","value":""},{"op":"replace","path":"/workspaces/1/SignIn/FullName","value":""},{"op":"add","path":"/workspaces/1","value":{"Launcher":{"Html":"","appName":"signin","_layout":"","_partialId":"","_editorOpened":false},"Launcher":{"Html":""},"SignIn":{"Uri":"","Html":"/SignIn/viewmodels/SignInPage.html","Username$":"","Password$":"","IsSignedIn":false,"Message":"","FullName":"","ImageUrl":"name{:}David Rosendahl{;}type{:}gravatar{;}value{:}40a6fa0f27249bfa29a0369afee0e150?d=monsterid"},"tunity_actionboard":{"Html":"/tu-common/master.html","Version":"v.","BuildTime":"2015-10-20 06:11:20","Modals":[],"UserMessage":{"Message":"","Type":"","Show$":false},"Command$":"","Ping$":0,"Title":""},"Html":"/sc/htmlmerger?SignIn=/SignIn/viewmodels/SignInPage.html&tunity_actionboard=/tu-common/master.html","AppName":"SignIn","PartialId":"/SignIn/viewmodels/SignInPage.html"}}]
```

**Comment by chrhol** [comment]
I have a solution for this. Want to spend a little time and see if It's possible to simplify it. Will probably push the fix before lunch.

**Comment by chrhol** [comment]
I pushed a fix for this to develop now. 

**Note**: When updating to a Starcounter version that contains this fix it is also needed to update the Launcher, I moved setting a field to there when a `LauncherWrapperPage` is created

**Comment by chrhol** [comment]
After discussion with @miyconst, just to make it more visible, that this is a hack (as usual) to make layout-information to be injected in the response. 

The proper solution is to implement #2690 to allow Launcher (or other app) to handle it and remove all magic code from serializer.

**Comment by warpech** [comment]
The problem still happens if the application URL does not match the assembly name.

For example, run Launcher + People app. In People, rename one of the handlers from `/people/organization` to `/people2/organization`.

The right part should have the same result as the left part (As long as `EnforceURINamespaces` is false). Currently it is not like that, which is depicted on the below screenshot.

<img width="1440" alt="screen shot 2016-02-15 at 12 59 14" src="https://cloud.githubusercontent.com/assets/566463/13048108/f92366b0-d3e3-11e5-99a4-599b73974ef2.png">

The dependency AppName/URL is still hardcoded somewhere in the merger code, and it should not. In my opinion, AppName of the merged response should be based on the main app that registered the handler.

@chrhol WDYT? This is a very long standing problem and it badly needs fixing. https://github.com/Starcounter/InvoiceDemo/issues/55, https://github.com/StarcounterSamples/SignIn/issues/7

**Comment by chrhol** [comment]
> For example, run Launcher + People app. In People, rename one of the handlers from /people/organization to /people2/organization.

How can you do that? I thought we had a hard requirement that the uri's needs to be prefixed with the appname? Or have you changed the appname of the whole People-app to People2?

**Comment by chrhol** [comment]
It's the launcher that handles this (with the hack I added) and this will also be the proper solution I guess. So if you don't use the same name in the request as the appname then the launcher needs to set the correct information.

in `LauncherHelper.cs`:

```csharp
static Response WrapInLauncher(Request req, String appName) {
    ...
    if (StarcounterEnvironment.AppName != appName && appNameForLayoutField != null)
        appNameForLayoutField.SetValue(p, appName); // Should be People2 from URI and not appName
    ...
    p.AppName = appName; // Should be People2 from URI, and not appName
    ...
}
```

**Comment by chrhol** [comment]
What exactly are the requirements on this? I'm feeling a little confused since we have done too many hacks for this instead of taking the time to do it properly :)

Is this correct?:
1. The resulting JSON should include a property `AppName` set to the original caller (for example People/People2) on each level that has a layout.
2. Each merged result should be namespaced (with the name from the URI or the name of the app?)
3. The namespace/appname in htmlmerger should correspond to the namespaces/appnames in 2)

It feels like I missed something.

**Comment by warpech** [comment]
> How can you do that? I thought we had a hard requirement that the uri's needs to be prefixed with the appname?

URIs should be prefixed with to avoiding collisions when running multiple apps. But this is a "soft requirement" that can be turned off with the `EnforceURINamespaces`.

> Or have you changed the appname of the whole People-app to People2?

No, I have only changed the URI prefix to "/people2" and kept the app name "People". This happens very often for people who do the tutorials, refactors, etc.

> Is this correct?:
1. The resulting JSON should include a property AppName set to the original caller (for example People/People2) on each level that has a layout.
2. Each merged result should be namespaced (with the name from the URI or the name of the app?)
3. The namespace/appname in htmlmerger should correspond to the namespaces/appnames in 2)

I think the below is correct:

1. The resulting JSON should include a property AppName set to the original caller (for example People/People2) on each level that has namespaces (= is a merged response).
2. Each merged result should be namespaced (with the AppName)
3. The namespace/AppName in htmlmerger should correspond to the namespaces/AppNames in 2)

Everywhere above AppName means `StarcounterEnvironment.AppName`. It might but be equal to the first segment of the URI, but that should not be assumed anywhere in the namespaces or htmlmerger.

**Comment by warpech** [comment]
I updated the page https://github.com/StarcounterPrefabs/Launcher/wiki/Merged-JSON-Response to show the current desired state

**Comment by chrhol** [comment]
Thanks @warpech for the clarifications!

**Comment by alemoi** [comment]
@chrhol do you need any help with this?

**Comment by warpech** [comment]
The solution is tracked in #2690

**Comment by chrhol** [comment]
We're getting close to have a proper solution for this issue in place. I've added a callback that is triggered when merging responses, and added an implementation together with @warpech in the `Launcher`.

What this means is internally in Starcounter, all extra magic stuff for layouts are finally removed from the serializer (and from Starcounter itself except the `Layout` class which probably should be moved a s well) and all layout and appname/workspace info comes from the Launcher.

As for the resulting viewmodel on the client it means that the layout-information will no longer be found in the root of each namespaced node as described in the [Basic](https://github.com/StarcounterPrefabs/Launcher/wiki/Merged-JSON-Response#required-for-basic-layout-management) section, but instead it will be added inside the `Launcher` namespace and look like the [Desired](https://github.com/StarcounterPrefabs/Launcher/wiki/Merged-JSON-Response#desired) section

The change is not yet merged to develop, and can be found in the following branches:
- https://github.com/Starcounter/Starcounter/tree/issue/2690
- https://github.com/StarcounterPrefabs/Launcher/tree/mergecallback

@miyconst, @tomalec: Could you take a look at the current solution and see if we missed something? If you want to try it (without compiling Starcounter yourself) I can provide you with a custom build.

**Comment by miyconst** [comment]
@chrhol it would be nice if you can upload a custom daily build, I don't have environments to compile Starcounter.

**Comment by per-samuelsson** [comment]
> @chrhol it would be nice if you can upload a custom daily build, I don't have environments to compile Starcounter.

You don't need a local one, just build one on the build server. Do you have access to that? `teamcity.starcounter.org`.

**Comment by per-samuelsson** [comment]
> What this means is internally in Starcounter, all extra magic stuff for layouts are finally removed from the serializer (and from Starcounter itself except the Layout class **which probably should be moved a s well**).

Would be really good if we do that too, IMO. Isn't it very specific to the default Launcher? Can't we just move it there?

**Comment by miyconst** [comment]
>You don't need a local one, just build one on the build server. Do you have access to that? `teamcity.starcounter.org`.

I do have access, will try that.

**Comment by warpech** [comment]
> > What this means is internally in Starcounter, all extra magic stuff for layouts are finally removed from the serializer (and from Starcounter itself except the Layout class which probably should be moved a s well).

> Would be really good if we do that too, IMO. Isn't it very specific to the default Launcher? Can't we just move it there?

Layout class was included in Starcounter on purpose. See the OP in  https://github.com/Starcounter/Starcounter/issues/2893

**Comment by per-samuelsson** [comment]
> Layout class was included in Starcounter on purpose. See the OP in #2893.

Thanks @warpech. I'm not sure I like the idea of having Starcounter include that class still, but I do now see the reasoning, and I don't have anything better to propose, so yeah, lets keep it as is.

**Comment by tomalec** [comment]
> Do you have access to that? teamcity.starcounter.org.
I don't :(

**Comment by warpech** [comment]
@chrhol can you put an installer in Dropbox, for those who don't have a VPN or TeamCity access?

**Comment by miyconst** [comment]
I just have did that. Available in my Exchange folder.

```
Starcounter-DevelopDailyBuilds-2.1.1382-Setup.exe
```

**Comment by chrhol** [comment]
> @chrhol can you put an installer in Dropbox, for those who don't have a VPN or TeamCity access?

I've added the installer konstantin made to the public folder. Will remove that version once we have merged the fix.

https://www.dropbox.com/s/a2lttshsaqbk5xx/Starcounter-DevelopDailyBuilds-2.1.1382-Setup.exe?dl=0

**Comment by chrhol** [comment]
> I just have did that. Available in my Exchange folder.

Haha, I was 2 seconds too late

**Comment by dan31** [comment]
@miyconst @warpech @per-samuelsson @chrhol What is the status of this one?

**Comment by per-samuelsson** [comment]
@dan31 

If I'm not wrong, this one depends on #2690, which is kind of the enabler to fix this. And that is what @chrhol is working on currently, I think.

**Comment by chrhol** [comment]
> If I'm not wrong, this one depends on #2690, which is kind of the enabler to fix this. And that is what @chrhol is working on currently, I think.

Well I'm not working on anything currently. I've been completely bedridden the last days with the flu (I suspect). But you are correct, we have one thing left to solve which I need to sit down with @alemoi and go through so we get it properly done.

**Comment by chrhol** [comment]
I've merged the changes for #2690 and the other needed fixes for the workspace-problem to develop (and pnext). Hopefully this issue can finally be considered solved.

I will wait until we see that everything works as expected since changes in Launcher is needed as well.

**Comment by warpech** [comment]
Assigning it on me to do final testing, based on the reproduction steps in the above comments.

**Comment by warpech** [comment]
I have successfully tested the following scenarios:

1. Going to Procurement page `/Procurement/purchase-order/…`
2. Sign in/out in GoogleSignIn app
3. In People, rename one of the handlers from `/people/organization` to `/people2/organization`
    - needs an additional fix in Launcher, but that's a different story: https://github.com/StarcounterPrefabs/Launcher/issues/208

In all of the cases, the problem with missing AppName is gone. 

Good job @chrhol!
