### ISSUE TITLE
Starting KitchenSink in default failed due to an unexpected problem

### ISSUE THREAD

**Issue by MLidstrom** [Starcounter/Starcounter#3298]
I got this when starting KitchenSink.

"Starting KitchenSink in default failed due to an unexpected problem. ("Object reference not set to an instance of an object."). (ScErrUnexpectedCommandException (SCERR10016))"

From the log (Date and source on both these messages are the same. Date 2016-01-25 16:53:06 and source Starcounter.Server.Commands):

Message -- ScErrServerCommandFailed (SCERR10011): The operation "Starting KitchenSink in default" failed.
Version: 2.1.1081.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

Message -- ScErrUnexpectedCommandException (SCERR10016): Starting KitchenSink in default failed due to an unexpected problem.
Version: 2.1.1081.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Administrator.Server.Managers.ServerManager.ServerModel_Changed(Object sender, EventArgs e) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 302
   at Administrator.Server.Model.Database.DatabaseApplications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 346
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Administrator.Server.Model.Database.InvalidateApplications() in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 621
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterInternalModelApi>b__8_2(String databaseName, Request request) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 282
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.PUT(String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Starcounter.Internal\Rest\Self.cs:line 177
   at Starcounter.Server.PublicModelProvider.UpdateDatabase(Database database) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Server\Starcounter.Server\PublicModelProvider.cs:line 82
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 189
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 483
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 514
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\BuildAgent\work\sc-develop-nightly-163\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2147467261

**Comment by miyconst** [comment]
cc @andwah

**Comment by per-samuelsson** [comment]
Hmm, I experienced something similar in **pnext** this morning - #3293 - and thought it was specific to that branch. But this is the standard stable version, right?

**Comment by MLidstrom** [comment]
It was the nightly 2.1.1081 from jan 22:nd.

**Comment by andwah** [comment]
I will take a look.

**Comment by per-samuelsson** [comment]
Bad practice to close user issues before they get the chance to verify them (reopening is not allowed if your not a team member). :smile: 

@MLidstrom is still experiencing this. I'll let him re-report it.

**Comment by MLidstrom** [comment]
From the log of the latest nightly:

ScErrServerCommandFailed (SCERR10011): The operation "Stopping DF436D76C4160219AD711FEA1E6F7512D71FC5AE" failed.
Version: 2.1.1123.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011.

ScErrUnexpectedCommandException (SCERR10016): Stopping DF436D76C4160219AD711FEA1E6F7512D71FC5AE failed due to an unexpected problem.
Version: 2.1.1123.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Administrator.Server.Managers.ServerManager.ServerModel_Changed(Object sender, EventArgs e) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 301
   at Administrator.Server.Model.Database.DatabaseApplications_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 346
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at Administrator.Server.Model.Database.InvalidateApplications() in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 655
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterInternalModelApi>b__8_2(String databaseName, Request request) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 281
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.PUT(String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Starcounter.Internal\Rest\Self.cs:line 177
   at Starcounter.Server.PublicModelProvider.UpdateDatabase(Database database) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Server\Starcounter.Server\PublicModelProvider.cs:line 82
   at Starcounter.Server.Commands.StopExecutableCommandProcessor.Execute() in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Server\Starcounter.Server\Commands\Processors\StopExecutableCommandProcessor.cs:line 151
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\BuildAgent\work\sc-develop-nightly-167\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 298
HResult=-2147467261

**Comment by per-samuelsson** [comment]
I also got this again, using the latest **pnext** nightly (2.3.605):

```
ScErrUnexpectedCommandException (SCERR10016): Starting database regina. failed due to an unexpected problem.
Version: 2.3.605.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10016.
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Administrator.Server.Managers.ServerManager.ServerModel_Changed(Object sender, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 302
   at Administrator.Server.Model.Server.OnChanged(Object sender, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Server.cs:line 194
   at Administrator.Server.Model.Database.OnChanged(Object sender, EventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 391
   at Administrator.Server.Model.Database.Database_PropertyChanged(Object sender, PropertyChangedEventArgs e) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 376
   at Administrator.Server.Model.Database.OnPropertyChanged(String fieldName) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 1245
   at Administrator.Server.Model.Database.InvalidateModel() in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Model\Database.cs:line 601
   at Administrator.Server.Managers.ServerManager.<>c.<RegisterInternalModelApi>b__8_2(String databaseName, Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Administrator\Server\Managers\ServerManager.cs:line 282
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1114
   at Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Internal\Rest\Self.cs:line 392
   at Starcounter.Self.PUT(String uri, String body, Byte[] bodyBytes, Dictionary`2 headersDictionary, UInt16 port, HandlerOptions ho) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Starcounter.Internal\Rest\Self.cs:line 177
   at Starcounter.Server.PublicModelProvider.UpdateDatabase(Database database) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\PublicModelProvider.cs:line 77
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.<>c__DisplayClass2_0.<Execute>b__2(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 75
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 483
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.Processors.StartDatabaseCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\Commands\Processors\StartDatabaseCommandProcessor.cs:line 78
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-39\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2147467261
```

A weird thing I noticed just before was that in the Administrator, I looked at a database and the status of the database was "Stopped" (or actually, the Start button was enabled), but when I looked at the applications, it showed for of them was running (and I disabled the cache and hit F5 number of times).

Checking the status with `staradmin list apps` showed me the correct result: no applications (in that database) was running.

**Comment by andwah** [comment]
Im trying tried to reproduce this, 

Do you have any more input on how to reproduce this?
* Is the other apps is running?
* Is there other open sessions (browser tab's with the administrator running?)
* Fresh start of scservice or had it been running for a while?
* does this Exception occurs everytime you start an app?

**Comment by per-samuelsson** [comment]
> A weird thing I noticed just before was that in the Administrator, I looked at a database and the status of the database was "Stopped" (or actually, the Start button was enabled), but when I looked at the applications, it showed for of them was running (and I disabled the cache and hit F5 number of times).

> Checking the status with `staradmin list apps` showed me the correct result: no applications (in that database) was running.

Here's an illustration of the above. Notice how the CLI indicates only two applications are running in "Regina" (which is the facit), and Administrator indicates four.

![image](https://cloud.githubusercontent.com/assets/2902045/12582943/6982a64a-c440-11e5-9e44-d6720d0d6a79.png)

**Comment by andwah** [comment]
@per-samuelsson Thanks for the illustration of the after effects of the problem. it's not a strange result, when the exception occurs the communication between the gui and server is affected in a bad way.

Do you have any clues of the state and what happened just before you got the exception?

**Comment by per-samuelsson** [comment]
> Do you have any clues of the state and what happened just before you got the exception?

Sorry, I don't. :disappointed: I tried to think through what I did, but I don't see any immediate pattern. The setup I have is a bit complicated, with 3 running databases and 4 applications starting/stopping/restarting in each (testing replication scenarios).

Once it does happen, it happens every time. I don't think I have restarted for quite some time and there is only a single administrator tab I use normally.

When I had the environment in the state the picture illustrate, I started another application ("SignIn") and the error occurred. But the application still started. Next time I did `staradmin list apps` all three apps where running.

**Comment by andwah** [comment]
@per-samuelsson Thanks.

I think i have found why this exception occurs.
When data was pushed on a  session (websocket), there was only a check that the session existed but not that the web socket also was connected (alive) to the client. I added a check for that. 58d862210e212c41747be700524bbd21a9306d3f

**Comment by MLidstrom** [comment]
No error message with nightly 2.1.1135.

**Comment by andwah** [comment]
@MLidstrom There has been no changes by me in the nightly, the fix was pushed about 2 hours ago.

The error does not occurs every time, only when the socket was closed by a time out or some other (unknown) event.

**Comment by careri** [comment]
I still have this #3314.
Any progress?

I can reproduce every time in VS:
1. F5 start
2. Do some debugging
3. Shift+F5 Stop
4. Fix code
5. F5, fails
6. F5 starts
7. Go to step2

**Comment by andwah** [comment]
@careri which starcounter version did you use?

**Comment by andwah** [comment]
The fix will be in nightly v2.1.1148 and up.

**Comment by dan31** [comment]
@per-samuelsson @chrhol is that an issue currently?
@andwah have you also added the fix into pnext?

**Comment by per-samuelsson** [comment]
> @per-samuelsson @chrhol is that an issue currently?

Hard to tell for sure o/c, but I haven't seen it until I last wrote here, so that last @andwah fix might have fixed it.

> @andwah have you also added the fix into pnext?

FWIW, I'm running **pnext** only since like a month, so my previous answer is in the light of that.

**Comment by andwah** [comment]
> have you also added the fix into pnext?

No, i pushed it to `develop`

**Comment by dan31** [comment]
Anything pushed to develop should also go into pnext. There is no autosync of features between develop and pnext. Please make sure today that all the fixes from develop you made are also in pnext. Thanks!

**Comment by per-samuelsson** [comment]
We haven't heard either @MLidstrom or @careri report that they have this still, so I think it's now in a state where we can consider it fixed.

I'm closing this. If you guys think thats wrong, just leave a beep and I'll reopen it again and we'll iterate over it again.
