### ISSUE TITLE
Starcounter admin panel query result visualisation problem

### ISSUE THREAD

**Issue by binte** [Starcounter/Starcounter#3390]
Surely someone had already mentioned this, but since I couldn't find it, I am hereby reporting the issue. 

After obtaining the results of a query, when we scroll right, it becomes impossible to understand the table, because the attributes' bar starts "floating". 

Also, when the table has too many attributes, I can't see them all.

**Comment by miyconst** [comment]
@binte thank your for reporting this. Could you please make some screenshots?

cc @warpech

**Comment by binte** [comment]
Completely forgot that! 

![screenshot1](https://cloud.githubusercontent.com/assets/5520287/13147770/856357b6-d65a-11e5-85de-c94713a95a5f.png)

**Comment by binte** [comment]
Completely forgot that! 

![untitled](https://cloud.githubusercontent.com/assets/5520287/13147832/c4ae51e6-d65a-11e5-8b42-88071f0decee.png)

**Comment by miyconst** [comment]
And provide which Starcounter version you are using, please :).

**Comment by binte** [comment]
Starcounter-Stable-2.1.177

**Comment by miyconst** [comment]
@warpech it's fixed in the later versions, right?

**Comment by warpech** [comment]
Yes, this is fixed in https://github.com/Starcounter/Starcounter/issues/2987, so it should not happen in nightlies

**Comment by miyconst** [comment]
@binte could you please check latest nightly and confirm that it is fixed?

**Comment by binte** [comment]
@miyconst I am sorry for the delay! I confirm it is working with the latest nightly (2.1.1389). No more floating attributes! BUT scrolling right and left is still not perfect! For a big number of attributes, during scrolling, sometimes it "jumps" to a different location.

**Comment by miyconst** [comment]
@binte could you please record a gif of the issue and post here?

**Comment by binte** [comment]
Good idea!

![animation](https://cloud.githubusercontent.com/assets/5520287/13674286/354aa0b6-e6dd-11e5-9fc3-658cf0953206.gif)
