### ISSUE TITLE
pnext: Removing a database field cause unload to fail (ScErrColumnHasNoProperty)

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3932]
Simply reproduced and deterministic. See reproducible steps below.

Version tested: `pnext / 2.3.0.4643`.

Possible duplicate of #3919. Somewhat similar to #3929, but in that case, unloading worked, but reloading failed (with another error), and that was in 2.2.

### How to reproduce
1. Create a new empty database.
2. Start an application with content listed as **app.cs (before)** below.
3. Stop the database.
4. Alter the content of the application to **app.cs (after)** (refactoring: removing a field).
5. Start the application.
6. Issue an unload (see error below):

**app.cs (before)**
```cs
using Starcounter;

namespace RemoveField
{
    [Database]
    public class Foo
    {
        public string Bar;
    }

    class Program
    {
        static void Main()
        {
            Db.Transact(() => { new Foo() { Bar = "Value" }; });
        }
    }
}
```

**app.cs (after)**
```cs
using Starcounter;

namespace RemoveField
{
    [Database]
    public class Foo { }

    class Program
    {
        static void Main()
        {
            Db.Transact(() => { new Foo(); });
        }
    }
}
```

**Error**
> [13:25:41, Critical, Starcounter (default)]
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception.
ScErrColumnHasNoProperty (SCERR6081): The column is not exposed with a property, it can not be accessed. Missing property for Foo.Bar
Version: 2.3.0.4643.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6081.
Version: 2.3.0.4643.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 534
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 85
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 521
HResult=-2146232828
---> System.Exception: ScErrColumnHasNoProperty (SCERR6081): The column is not exposed with a property, it can not be accessed. Missing property for Foo.Bar
Version: 2.3.0.4643.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6081.
   at Starcounter.Reload.GetPropertyName(Column col) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter\Mock\Reload.cs:line 55
   at Starcounter.Reload.<>c.<CreateSelectStatementForTable>b__5_0(Column col) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter\Mock\Reload.cs:line 100
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Concat(IEnumerable`1 values)
   at Starcounter.Reload.CreateSelectStatementForTable(Table tbl) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter\Mock\Reload.cs:line 99
   at Starcounter.Reload.Unload(String fileName, UInt64 shiftId, Boolean unloadAll) in C:\TeamCity\TeamCity10\buildAgent\work\sc-pnext-nightly-317\Level1\src\Starcounter\Mock\Reload.cs:line 239
   at UnloadDatabase.Program.Main(String[] args) in c:\Program Files\Starcounter\cli-apps\UnloadDatabase.cs:line 34
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6081

**Comment by k-rus** [comment]
Good finding. This is due to different way of accepting database refactoring. Now removing column does nothing with the database. So unload needs to be fixed, but then the question is what should we do in this situation? Should we unload all the data, but then reload will fail, since the column will not be created when the app will be loaded? Or should we ignore the columns, which are not presented in CLR classes?

It feels like our user want the second behaviour. But it means data lose.

Another approach is to add flag ignore unknown columns, i.e., columns not known in CLR.

**Comment by dan31** [comment]
@k-rus question: how it this resolved with 2.3 RC?

**Comment by k-rus** [comment]
The issue is with the old unload. The issue is not resolved.

**Comment by miyconst** [comment]
>The issue is not resolved.

I don't think it is going to be ever resolved in the old `unload` tool. The solution is to use the new `StarDump` tool. Am I right @k-rus?

**Comment by k-rus** [comment]
> I don't think it is going to be ever resolved in the old unload tool. The solution is to use the new StarDump tool. Am I right @k-rus?

@dan31 asks how it is resolved in 2.3. And this particular issue is not resolved and not planned for resolution.
I assume same as @miyconst that new tool can be used.

**Comment by per-samuelsson** [comment]
Isn't old `staradmin unload/reload` somewhat compatible with stardump invocation? Then why dont we just redirect the former to the later and that will fix it all? I mean, `staradmin` would be really trivial to adapt to that. Just take a look at the code.
